ci: Only allow publishing docs from master branch or valid tag
When running a manual workflow, there's a "publish" boolean input.
However we don't want ci-test-docs branch may also be a trigger for
updating the CI infra for docs: we don't want to inadvertently also
publish the docs when running that pipeline.

Signed-off-by: Lucas De Marchi <demarchi@kernel.org>

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -106,6 +106,12 @@ jobs:
           if [[ "$PUBLISH" == "false" ]]; then
             echo "publish=false" >> $GITHUB_OUTPUT
           elif [[ "$PUBLISH" == "true" ]]; then
+            # this is a manual workflow, only allow to publish if being executed from master branch
+            # or a tag. We don't want a build from ci-test-docs to end up publishing anything
+            if [[ "${GITHUB_REF}" != refs/heads/master && "${GITHUB_REF}" != refs/tags/* ]]; then
+              echo "::error::Can't publish from branch != master or a valid tag (ref=${GITHUB_REF}"
+              exit 1
+            fi
             echo "publish=true" >> $GITHUB_OUTPUT
           elif [[ "${GITHUB_REF}" == refs/heads/master || "${GITHUB_REF}" == refs/tags/* ]]; then
             echo "publish=true" >> $GITHUB_OUTPUT
